# Generated by Django 3.1.1 on 2020-10-26 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoringData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_id', models.BigIntegerField()),
                ('timestamp', models.DateTimeField()),
                ('activity_name', models.CharField(max_length=100)),
                ('metadata_os', models.CharField(max_length=100)),
                ('metadata_ean', models.BigIntegerField()),
            ],
            options={
                'verbose_name': 'Monitoring Data',
                'verbose_name_plural': 'Monitoring Data',
            },
        ),
        migrations.CreateModel(
            name='ProductReviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_id', models.BigIntegerField()),
                ('product_ean', models.BigIntegerField()),
                ('selected_indicator_main_id', models.CharField(max_length=100)),
                ('selected_indicator_secondary_id', models.CharField(max_length=100)),
                ('free_text_indicator', models.TextField()),
                ('price_checkbox_selected', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Product Reviews',
                'verbose_name_plural': 'Product Reviews',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_id', models.BigIntegerField()),
                ('timestamp', models.CharField(max_length=50)),
                ('products', models.BigIntegerField()),
            ],
            options={
                'verbose_name': 'Products',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_id', models.BigIntegerField()),
                ('status', models.CharField(max_length=100)),
                ('product_type_preference', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Users',
                'verbose_name_plural': 'Users',
            },
        ),
    ]
