# Generated by Django 3.2.5 on 2021-07-06 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaticIndicatorCategories',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('icon_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'StaticIndicatorCategories',
                'verbose_name_plural': 'StaticIndicatorCategories',
            },
        ),
        migrations.CreateModel(
            name='StaticIndicators',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('category_id', models.CharField(max_length=100)),
                ('icon_name', models.CharField(max_length=100)),
                ('general_description', models.TextField()),
            ],
            options={
                'verbose_name': 'StaticIndicators',
                'verbose_name_plural': 'StaticIndicators',
            },
        ),
        migrations.CreateModel(
            name='StaticProducts',
            fields=[
                ('code', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('type', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('provider', models.CharField(max_length=100)),
                ('image_url', models.TextField()),
                ('indicators_0_indicator_id', models.CharField(max_length=100)),
                ('indicators_0_indicator_description', models.TextField()),
                ('indicators_1_indicator_id', models.CharField(max_length=100)),
                ('indicators_1_indicator_description', models.TextField()),
                ('indicators_2_indicator_id', models.CharField(max_length=100)),
                ('indicators_2_indicator_description', models.TextField()),
            ],
            options={
                'verbose_name': 'StaticProducts',
                'verbose_name_plural': 'StaticProducts',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('participant_id', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('requested', 'requested'), ('valid', 'valid'),('archived', 'archived')], default='requested', max_length=100)),
                ('platform', models.CharField(choices=[('ios', 'ios'), ('android', 'android')], max_length=100, null=True)),
                ('phase2_date', models.DateField(blank=True, max_length=100, null=True)),
                ('product_category_1', models.CharField(blank=True, max_length=100, null=True)),
                ('product_category_2', models.CharField(blank=True, max_length=100, null=True)),
                ('product_category_3', models.CharField(blank=True, max_length=100, null=True)),
                ('product_category_4', models.CharField(blank=True, max_length=100, null=True)),
                ('indicator_category_1', models.CharField(blank=True, max_length=100, null=True)),
                ('indicator_category_2', models.CharField(blank=True, max_length=100, null=True)),
                ('indicator_category_3', models.CharField(blank=True, max_length=100, null=True)),
                ('indicator_category_4', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Users',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='ProductReviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_ean', models.BigIntegerField()),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('selected_indicator_main_id', models.CharField(blank=True, max_length=100, null=True)),
                ('selected_indicator_secondary_id', models.CharField(blank=True, max_length=100, null=True)),
                ('free_text_indicator', models.TextField(blank=True, null=True)),
                ('price_checkbox_selected', models.BooleanField()),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GoodnessGroceries.users')),
            ],
            options={
                'verbose_name': 'Product Reviews',
                'verbose_name_plural': 'Product Reviews',
            },
        ),
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('device_token', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GoodnessGroceries.users')),
            ],
            options={
                'verbose_name': 'Devices',
                'verbose_name_plural': 'Devices',
            },
        ),
        migrations.CreateModel(
            name='CashierTicketProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.CharField(max_length=100)),
                ('product', models.BigIntegerField()),
                ('reviewed', models.BooleanField(default=False, null=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GoodnessGroceries.users')),
            ],
            options={
                'verbose_name': 'CashierTicketProducts',
                'verbose_name_plural': 'CashierTicketProducts',
            },
        ),
    ]
