# Generated by Django 3.1.1 on 2020-10-22 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoodnessGroceries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_id', models.IntegerField()),
                ('products_0_product_ean', models.CharField(max_length=50)),
                ('products_1_product_ean', models.CharField(max_length=50)),
                ('products_2_product_ean', models.CharField(max_length=50)),
                ('products_3_product_ean', models.CharField(max_length=50)),
                ('products_4_product_ean', models.CharField(max_length=50)),
                ('products_5_product_ean', models.CharField(max_length=50)),
                ('products_6_product_ean', models.CharField(max_length=50)),
                ('products_7_product_ean', models.CharField(max_length=50)),
                ('products_8_product_ean', models.CharField(max_length=50)),
                ('products_9_product_ean', models.CharField(max_length=50)),
                ('products_10_product_ean', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='ProductsCashierTickets',
        ),
    ]
