# Generated by Django 3.2.5 on 2021-07-06 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GoodnessGroceries', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashierticketproducts',
            options={'verbose_name': 'Cashier Ticket Products', 'verbose_name_plural': 'Cashier Ticket Products'},
        ),
        migrations.AlterField(
            model_name='cashierticketproducts',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='devices',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='GoodnessGroceries.users'),
        ),
    ]
