# Generated by Django 3.1.1 on 2020-10-24 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoodnessGroceries', '0002_auto_20201022_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='participant_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='products_0_product_ean',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='products_10_product_ean',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='products_1_product_ean',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='products_2_product_ean',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='products_3_product_ean',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='products_4_product_ean',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='products_5_product_ean',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='products_6_product_ean',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='products_7_product_ean',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='products_8_product_ean',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='products_9_product_ean',
            field=models.BigIntegerField(),
        ),
    ]
