# Generated by Django 3.2.5 on 2021-07-06 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GoodnessGroceries', '0002_auto_20210706_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devices',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GoodnessGroceries.users'),
        ),
    ]
