# Generated by Django 3.1.1 on 2020-11-11 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoodnessGroceries', '0002_auto_20201105_1724'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.BigIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('type', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('provider', models.CharField(max_length=100)),
                ('image_url', models.URLField()),
                ('indicators_0_indicator_id', models.BigIntegerField()),
                ('indicators_0_indicator_description', models.CharField(max_length=1000)),
                ('indicators_1_indicator_id', models.BigIntegerField()),
                ('indicators_1_indicator_description', models.CharField(max_length=1000)),
                ('indicators_2_indicator_id', models.BigIntegerField()),
                ('indicators_2_indicator_description', models.CharField(max_length=1000)),
            ],
        ),
    ]
