# Generated by Django 3.1.13 on 2021-07-12 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GoodnessGroceries', '0003_alter_devices_participant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashierticketproducts',
            options={'verbose_name': 'Cashier Ticket Product', 'verbose_name_plural': 'Cashier Ticket Products'},
        ),
        migrations.AlterModelOptions(
            name='devices',
            options={'verbose_name': 'Device', 'verbose_name_plural': 'Devices'},
        ),
        migrations.AlterModelOptions(
            name='productreviews',
            options={'verbose_name': 'Product Review', 'verbose_name_plural': 'Product Reviews'},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': 'Participant', 'verbose_name_plural': 'Participants'},
        ),
        migrations.RenameField(
            model_name='cashierticketproducts',
            old_name='product',
            new_name='product_ean',
        ),
    ]
