# Generated by Django 3.1.1 on 2020-11-11 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoodnessGroceries', '0003_staticproducts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticproducts',
            name='indicators_0_indicator_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='staticproducts',
            name='indicators_1_indicator_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='staticproducts',
            name='indicators_2_indicator_id',
            field=models.CharField(max_length=100),
        ),
    ]
