# Generated by Django 3.1.13 on 2021-07-12 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoodnessGroceries', '0004_auto_20210712_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashierticketproducts',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
