# Generated by Django 3.1.1 on 2020-11-11 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoodnessGroceries', '0004_auto_20201111_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticproducts',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='staticproducts',
            name='indicators_0_indicator_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='staticproducts',
            name='indicators_1_indicator_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='staticproducts',
            name='indicators_2_indicator_description',
            field=models.TextField(),
        ),
    ]
