# Generated by Django 3.1.13 on 2021-07-14 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoodnessGroceries', '0005_auto_20210712_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='status',
            field=models.CharField(choices=[('requested', 'requested'), ('valid', 'valid'), ('archived', 'archived')], default='requested', max_length=100),
        ),
    ]
