# Generated by Django 3.1.1 on 2020-11-11 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoodnessGroceries', '0005_auto_20201111_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticproducts',
            name='image_url',
            field=models.TextField(),
        ),
    ]
