# Generated by Django 3.1.1 on 2020-11-12 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoodnessGroceries', '0006_auto_20201111_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticIndicatorCategories',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('icon_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='StaticIndicators',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('category_id', models.CharField(max_length=100)),
                ('icon_name', models.CharField(max_length=100)),
                ('general_description', models.TextField()),
            ],
        ),
    ]
