# Generated by Django 3.1.13 on 2021-07-16 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GoodnessGroceries', '0006_auto_20210714_0753'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Devices',
        ),
    ]
