# Generated by Django 3.1.1 on 2020-11-12 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GoodnessGroceries', '0007_staticindicatorcategories_staticindicators'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staticindicatorcategories',
            options={'verbose_name': 'StaticIndicatorCategories', 'verbose_name_plural': 'StaticIndicatorCategories'},
        ),
        migrations.AlterModelOptions(
            name='staticindicators',
            options={'verbose_name': 'StaticIndicators', 'verbose_name_plural': 'StaticIndicators'},
        ),
        migrations.AlterModelOptions(
            name='staticproducts',
            options={'verbose_name': 'StaticProducts', 'verbose_name_plural': 'StaticProducts'},
        ),
    ]
