# Generated by Django 3.1.1 on 2020-11-14 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoodnessGroceries', '0008_auto_20201112_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='product_category_3',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='product_category_4',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
