# Generated by Django 3.1.1 on 2020-11-14 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GoodnessGroceries', '0009_auto_20201114_1439'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='CashierTicketProducts',
        ),
    ]
