# Generated by Django 3.1.1 on 2020-11-14 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GoodnessGroceries', '0010_auto_20201114_1519'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashierticketproducts',
            options={'verbose_name': 'CashierTicketProducts', 'verbose_name_plural': 'CashierTicketProducts'},
        ),
    ]
