# Generated by Django 3.1.1 on 2020-11-14 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GoodnessGroceries', '0011_auto_20201114_1519'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cashierticketproducts',
            old_name='products',
            new_name='product',
        ),
    ]
