# Generated by Django 3.1.1 on 2020-11-16 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GoodnessGroceries', '0012_auto_20201114_1558'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monitoringdata',
            old_name='metadata_os',
            new_name='metadata',
        ),
        migrations.RemoveField(
            model_name='monitoringdata',
            name='metadata_ean',
        ),
    ]
