# Generated by Django 3.1.1 on 2020-11-16 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoodnessGroceries', '0013_auto_20201116_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashierticketproducts',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
