# Generated by Django 3.1.1 on 2020-11-16 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoodnessGroceries', '0014_cashierticketproducts_reviewed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staticproducts',
            name='id',
        ),
        migrations.AlterField(
            model_name='staticproducts',
            name='code',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
