# Generated by Django 3.1.1 on 2020-11-17 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoodnessGroceries', '0015_auto_20201116_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashierticketproducts',
            name='reviewed',
            field=models.NullBooleanField(default=False),
        ),
    ]
