# Generated by Django 3.1.1 on 2020-11-19 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GoodnessGroceries', '0018_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
