# Generated by Django 3.1.3 on 2020-11-20 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GoodnessGroceries', '0019_delete_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='status',
        ),
    ]
