# Generated by Django 3.1.3 on 2020-11-20 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoodnessGroceries', '0020_remove_users_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='status',
            field=models.CharField(choices=[('requested', 'requested'), ('valid', 'valid')], default='requested', max_length=100),
        ),
    ]
