# Generated by Django 3.1.3 on 2020-11-23 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoodnessGroceries', '0022_productreviews_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='indicator_category_1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='indicator_category_2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='indicator_category_3',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='indicator_category_4',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
