# Generated by Django 3.1.3 on 2020-12-14 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GoodnessGroceries', '0023_auto_20201123_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreviews',
            name='static_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='GoodnessGroceries.staticproducts'),
        ),
    ]
