# Generated by Django 3.1.3 on 2020-12-14 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GoodnessGroceries', '0027_auto_20201214_1424'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productreviews',
            old_name='static_product',
            new_name='product_name',
        ),
    ]
