"""
Django settings for GoodnessGroceries_Project project.

Generated by 'django-admin startproject' using Django 3.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""
from pathlib import Path
import os.path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'w#$n6c9zj)$^z7+q@v77$7luu$ulfdm__-)8i6+mf_pen8qt2!'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': 'debug.log',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file'],
            'level': 'DEBUG',
            'propagate': True,
        },
    },
}

ALLOWED_HOSTS = [
    'www.goodnessgroceries.com',
    'goodnessgroceries.com',
    'localhost',
    '127.0.0.1',
    '1279804155cb.ngrok.io'
]


# Application definition

INSTALLED_APPS = [
    'GoodnessGroceries.apps.GoodnessGroceriesConfig',
    'Users.apps.UsersConfig',
    'crispy_forms',
    'rest_framework',
    'push_notifications',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'GoodnessGroceries_Project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'GoodnessGroceries_Project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        "NAME": "goodness_groceries",
        #"USER": "flavio",
        "USER": "gguser",
        #"PASSWORD": "3G03BxsT4CZA",
        "PASSWORD": "gnfHhfh74nj&",
        "HOST": "localhost",
        "PORT": "5432",
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'CET'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/
STATIC_ROOT = '/home/admin/git/BSP3/GoodnessGroceries/static'
STATIC_URL = '/static/'


#STATICFILES_DIRS = ('/home/admin/git/BSP3/GoodnessGroceries/static',)
#    os.path.join(BASE_DIR, "static_csv_files")
# ]

CRISPY_TEMPLATE_PACK = 'bootstrap4'

LOGIN_REDIRECT_URL = 'GoodnessGroceries-home'
LOGIN_URL = 'login'

DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'

PUSH_NOTIFICATIONS_SETTINGS = {
    "FCM_API_KEY": "AAAATxb0bbc:APA91bH1RYXYCCHXaRWIPUj8ambOgBMBt3hQuNm2htjtsa9wrBNffBB_p6u15Jl_0pBtragKidI_4pIJ0BFlFeyl9Fp39ZkF_-n2GCS0dP34nRrZOubmNYadem4rLsEE2Pq9rUoBJ7NA",
    "APNS_AUTH_KEY_PATH": os.path.join(BASE_DIR, "apns_secret_key.p8"),
    "APNS_AUTH_KEY_ID": "399Y94M863",
    "APNS_TEAM_ID": "6733725FT8",
    "APNS_TOPIC": "lu.uni.bicslab.goodness.groceries",
    "APNS_USE_SANDBOX": False,
    "USER_MODEL": "GoodnessGroceries.Users",
}
